spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: test_route
            uri: https://www.rlfit.cn
            predicates:
              - Query=url,rlf
          - id: admin_route
            uri: lb://renren-fast
            predicates:
              - Path=/**
#            filters:
#              - RewritePath=/api/(?<segment>/?.*),/$\{segment}


